services:
    python:
        stdin_open: true
        tty: true
        container_name: ascii
        volumes:
            - /Users/zen/github/ASCII-generator:/data
        image: zhangyiming748/ascii:latest
        command: bash
        restart: unless-stopped